### ISSUE TITLE
jäsenanomuksesta sähköpostivahvistus?

### ISSUE THREAD

**Issue by janirutanen** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#1]
Hei www.
Tässä palautetta sivujen toimivuudesta (tai päinvastoin!)
Terveisin Eeva

-------- Välitetty viesti / Fwd.Msg --------
Hei!

Tein eilen tyttäreni henkilöjäsenanomuksenverkossa. 
Palvelu ei lähetä ilmoituksen vastaanottokuittausta. Voisiko palvelua kehittää vai teinkö ilmoituksen jotenkin puutteellisesti?

**Comment by kimmov-kipe** [comment]
Ilmoitus näkyi tulevan, kun testasimme. Sähköpostista ei ilmennyt lähetettyjä tietoja, vaikka se niin antoikin ymmärtää, lisättiin tiedot tulemaan jatkossa myös sähköpostissa.
