### ISSUE TITLE
Tiimikoulutusten ilmoittautumisten asetukset hajalla?

### ISSUE THREAD

**Issue by santeripalin** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#10]
Tiimikoulutuksiin voi jostain syystä ilmoittautua monta kertaa sama ihminen tai sitten ilmoittautuminen monistuu jostakin syystä. Tarkistin parin koulutuksen asetukset ja niissä on kyllä päällä esto, että ihminen voisi ilmoittautua vain kerran tiimikoulutukseen. Kalevi Rae laittoi samasta sähköpostia.

**Comment by janirutanen** [comment]
Tämä lisätty Davidille, koska www ei voi tehdä asialle mitään.

**Comment by kimmov-kipe** [comment]
Korjattu.
