### ISSUE TITLE
Flooding-tilanteen purkaaminen - toimiston työkalu

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#16]
Yleisöryntäyksessä 1.11. melkein aina tapahtuu floodin-tilanne:
![ekap-virheilm](https://user-images.githubusercontent.com/16022208/68530894-4ed50000-0315-11ea-8e96-20f9208539bf.jpeg)

Tilanne poistetaan tyhjentämällä flood-taulu.

Ehdotuksena on tehdä toimiston työkalu, joka sen tekee. Rittääkö SQL kysely?

**Comment by uumas** [comment]
Tämä ei ole enää tarpeellinen, koska taustalla oleva ongelma on korjattu (#17).
