### ISSUE TITLE
Flooding-tilanteen ehkäisy - parametrien säätö

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#17]
Flooding-tilanne syntyy, kun virheellisten kirjauttumisten määärä ylittää asetetun rajan. Ilmeisesti kyse on rajasta IP-oositetta kohti. Mahdolliset säädöt ovat tässä:

// Set per-IP failed login attempt limit and window.
variable_set('user_failed_login_ip_limit', 10); // Changed from 50 attempts to 10.
variable_set('user_failed_login_ip_window', 1800); // Changed from 3600s to 1800s.

**Comment by lanttupeikko** [comment]
Selvitettävä nykyiset arvot JA korjattava ne sopivalle tasolle. Flooding-ongelmien ratkaisua varten on saatavilla valmiita moduuleita, mutta niitä olisi tutkittava, testattava ja (jos/kun sopiva moduuli löytyy) asennettava. Drivessa on dokumentointia moduulien asentamisesta ym.

**Comment by uumas** [comment]
Se vaati hieman Sangelta vastauksen kalastelua ja drupalin konfiguraatiosyntaxin kanssa ~tunnin tappelua, mutta nyt drupalin pitäisi nähdä käyttäjän oikea ip-osoite, eikä kaikille reverse proxyn osoitetta. Tämä siis tarkoittaa, että drupal kestää _jokaiselta_ käyttäjältä saman verran epäonnistuneita kirjautumisia per ajanyksikkö kuin se ennen kesti kaikilta käyttäjiltä yhteensä (käyttäjä = ip-osoite).
