### ISSUE TITLE
Raportien päivitys ilmojäsenyysten kohdalla

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#18]
Ilmojäsenyydet puuttuvat näistä:
-ilmoittautumistilannesivu

**Comment by aevik** [comment]
Vasta hakemustasolla olevat jäsenyydet eivät ole tähänkään mennessä sisältyneet jäsentilastoihin.

Tieto on hyvä päivittää leiriläisten jäseneksi ilmoittautumisen seurantaan (leirilaistilanne-moduuli) myöhemmin. Akuuttia tarvetta ei ole, koska normaalisti vuoden aikana seurataan vain jo liittyneiden jäsenten määrää, ja leirilaistilanne-moduulin erittelyä tarvitaan vasta, kun jo leirikesän ollessa käynnissä kannustetaan leiritiimejä heruttelemaan leiriläisiä jäseniksi.

**Comment by anwolski** [comment]
Antoni on toteuttanut ajantasaisen hakemusten tilastosivun
https://www.protu.fi/tilastot/hakemukset

Se voi täyttää esitetyn tarpeen.

**Comment by anwolski** [comment]
Korvaava ratkaisu tehty.
