### ISSUE TITLE
Ilmoittautumislomake - jatkisialennus puuttuu

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#19]
Hintalaskuri ei ota huomioon lerityyppiä 'jatkoleiri', jossa on eri jäsenalennus kuin muilla leireillä

**Comment by aevik** [comment]
Olisi tärkeää saada selkeä listaus siitä, mitä kaikkia uusia arvoja tarvitaan.

Ilmeisesti tarvitaan:
- jäsenalennus syysleirille
- jäsenalennus muille jatkoleireille
- vähävaraisuusalennus syysleirille
- vähävaraisuusalennus muille jatkoleireille

Koska kesä- ja talvijatkis ovat yhtä pitkiä, ei niihin tarvittane eri hintoja.

Yleisesti ottaen ei kannata sen paremmin www-työryhmän työmäärän vuoksi kuin asetusten virheettömänä pitämisen takaamiseksikaan luoda tarpeettoman monia eri variaatioita, esim. mahdollisuus asettaa oma alennuksen määrä jokaiselle eri leirityypille. Järjestelmä kannattaa suunnitella linjassa Protun markkinointistrategian kanssa (mihin tällä hetkellä kuulunee yksinkertaisuus), ja Protun markkinointikäytäntöjen ei myöskään kannata olla poukkoilevia ja laskea järjestelmämuutosten varaan.

**Comment by anwolski** [comment]
Tehty
