### ISSUE TITLE
Jäsen ei pääse näkemään asiakasnumeroaan Protun sivuilta

### ISSUE THREAD

**Issue by janirutanen** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#2]
> Aatu Komsi <aatu.komsi@protu.fi> 2.10.2015
> 
> Tein äsken Protun pankkitilille tilisiirron, ja - kuten pitikin - verkkopankkiohjelma tarjosi minulle mahdollisuutta tehdä e-laskusopimus Protun kanssa.
> 
> Valitettavasti e-laskusopimus edellytti minua antamaan oman asiakasnumeroni sopimuksen tekemiseksi. Econetin asiakasnumero on kuitenkin lähtökohtaisesti piilotettu jäsentiedoista normijäsenen nähtäviltä. Jos olisin juuri saanut jäsenmaksulaskun, siitä se varmastikin olisi paljastunut, mutta nyt jouduin kurkkaamaan sen käyttäjätililtäni admin-tunnustani käyttäen.
> 
> Tämä kannattanee korjata Drupal 7 -uudistuksen yhteydessä - ja tietty samalla laittaa kentän otsikoksi esim. "Asiakasnumero jäsenmaksun e-laskusopimusta varten" tms.

Onkohan tämä korjattu?

**Comment by aevik** [comment]
Tehty. Kentän otsikko säädetty muotoon "Asiakasnumero e-laskusopimusta varten". Täyttöohjetekstiä ei valitettavasti saatu mukaan, koska nykyinen profiilisivun leiska ei laita niitä näkyville. Tämä ei kuitenkaan liene kauhea ongelma.
