### ISSUE TITLE
Ilmoittautumislomake - Poista -toiminto ei poistaa jäsenyyttä eikä alennushakemusta

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#20]
Jos ilmoittautunut käyttäjä poistaa itse ilmoittautumisen, mutta on hakenut jäsenyyttä tai alennusta, nämä hakemukset eivät poistu. Tarkoitus on, että ilmoittautumisen peruuminen poistaa myös siihen liittyvät hakemukset.

**Comment by aevik** [comment]
Olennaisinta on, että lomakkeella kerrotaan, että jäsen- ja alennushakemukset eivät poistu. Lisäksi jäsen- ja alennushakemusten ylläpitonäkymä (Protulomakkeet-moduulin versiosta 1.2 eteenpäin) listaa aina hakemuksen yhteydessä myös leirin, jolle henkilö on ilmoittautunut. Jos ilmoittautuminen on poistettu, leiriäkään ei listalta löydy. Nämä tällaiset "jämät" on siis joka tapauksessa helppo huomata hakemusten käsittelyssä ja poistaa käsin.

Haluttaessa moduulin myöhempään jatkokehitykseen voidaan ottaa se, että jos käyttäjä poistaa ilmoittautumisen, myös hakemukset poistuvat. Se ei kuitenkaan ole ihan pieni juttu korjata, ennen kaikkea siksi, koska se vaatii paljon testausta virheiden varalta,

**Comment by anwolski** [comment]
> _listaa aina hakemuksen yhteydessä myös leirin, jolle henkilö on ilmoittautunut. Jos ilmoittautuminen on poistettu, leiriäkään ei listalta löydy. Nämä tällaiset "jämät" on siis joka tapauksessa helppo huomata hakemusten käsittelyssä ja poistaa käsin._

Tämä ehdotus on väärä yleisessä tapauksessa. Yleensä tällainen käyttäjä vain vaihtaa leirin, eri ilmoittaudu toiselle (tämä on todettu). Hän on tehnyt sen siinä uskossa, että jäsenhakemus pysyy, ja näinkin ilmoittautumislomake on hänelle kertonut. Niitä ei saisi poistaa. Olen itse käsin korjannut sinne uuden leirin rid (jonka hain uid:kautta). Oli yksi tapaus, jossa uutta rid:iä ei ollut, eli käyttäjä ei ilmoittautunut toiselle leirille. Poistin sen hakemuksen.

**Comment by anwolski** [comment]
Kiirellisyys: minusta tämä on kiirellisempi kuin "ei kiirellinen" koska niin kaun, kun tämä ei ole totetutettu, "Leiri-ilmoittautumiset" -työkalu näyttää tyhjän leirin, jos käyttäjä on itse vaihtanut leirin toiseen. Tämä toki voidaan korjata työkalussa hakemalla oikea rid ja leiri uid:n kautta (mitä myös ehdotin), mutta pitkjänteisempi olisi totetuttaa tämä ilmoituksen poisto.

**Comment by anwolski** [comment]
Alennushaemuksen olisi myös hyvä poistua. On ollut tapauksia, jossa käyttäjä on tehnyt kaksi alennuhakemusta, koska järjestelmä tarjoaa alennushakemuksen tekemistä joka kertaa, kun käyttäjä teke toisen (tai kolmanneen tai ...) kerran ilmoittautumisen. Tupla-alennushakemukset aiheuttavat turhaa hämminkiä laskutusvaiheessa.

**Comment by anwolski** [comment]
Toteutettu hook_entity_delete - hook:in avulla. Hakemukset poistetaan tietokannasta, kun ilmoittautuminen poistuu.
