### ISSUE TITLE
Ilmoittautumislomake - toimisto ei pysty lisäämään ilmohakemusta tai alennushakemusta

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#22]
Joskus toimisto joutuu itse tekemään ilmoittautumisen käyttäjän puolesta (esim. käyttäjan kirjautumisongelmien takia) Tällöin käytetään lomakkeella olevaa kontrollia **"This registration is for**". Jos kuitenkin toimisto erehtyy hakemaan myös jäsenyyttä tai alennusta, ne kirjataan toimiston käyttäjätilille.

Ehdotukset:
a) laajenetaan "This registration is for" koskeman myös hakemuksia
tai/ja
b) annetaan toimistolle käyttöön mahdollisuus lisätä niitä erikseen käyttäjän nimellä

**Comment by aevik** [comment]
Protulomakkeet-moodulin versio 1.2 tarjoaa toimistolle mahdollisuuden lisätä hakemukset käsin (vaihtoehto b) - tosin ei käyttäjän nimellä vaan uid:llä.

**Comment by anwolski** [comment]
Tässä tapauksessa olsi hyvä olla jokin lukko, joka estää toimistoa käyttämään vahingossa tätä ilmoittautumisen lomakkeen osaa.

**Comment by aevik** [comment]
Periaatteessa voidaan myöhemmin ehkä lisätä jossakin versiossa 1.3 tai 1.4 koodi, joka blokkaa kaikilta Toimisto-roolillisilta mahdollisuuden käyttää laajennettua lomaketta. Tästä toki aiheutuisi lisäongelmia: onko juuri Toimisto-rooli oikea rajaus?  Jos ei, mikä rajaus olisi paitsi toimiva myös muistettavissa? Entä miten toimisto voi havaita, missä kunnossa lomake on, jos lomakkeen toiminnot on muutettu toimistolle rajatummiksi?

Itse jättäisin tämän nyt jatkokehitykseen ja lähtisin siitä, että leiri-ilmoittautumisten käsin syöttämiselle on annettu käyttöohjeet, jotka toimiston on opeteltava ja muistettava. Tämä olisi jatkohallinnan kannalta aika iso homma vain parin ihmisen perehdyttämisen ja opettelun vuoksi. 

(Tarkennus: Se, että merkitsin itseni tämän hoitajaksi ei koske tätä myöhemmin esitettyä lisätoimintoa.)

**Comment by anwolski** [comment]
Lisätty työkaluun
