### ISSUE TITLE
Ilmoittautumislomake - toimistolle mahdollisuus lisäätä ja poistaa hakemuksia

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#23]
Kts. myös #22 ja #20 

Toimistolla on operaattivista tarvetta lisätä ilmohakemuksi aja alennushalemuksia koska
- toimisto luo ilmoittautumisen (kts #22 )
- Käyttäjä on uhonhtanut lisätä ilmohakemksen tai alennushakemuksen

Samalla tarve poistaa (fyysisesti tai loogisesti) hakemuksia johtuu näistä:
- käyttäjä on hakenut ne vahingossa
- käyttäjä on poistanut ilmoittautumisen (kts #20  )

**Comment by aevik** [comment]
Protulomakkeet-moduulin versio 1.2 julkaistaan näinä päivinä ja se sisältää ylläpidon mahdollisuuden syöttää ilmoittamalleen henkilölle jäsen- tai alennushakemuksen siinä missä henkilö itse ilmoittautumislomakkeellakin. (Tämä ei ole kaikista helpointa, mutta mahdollista ja ohjeistettu. Oletuksena on, että uusien hakemusten tekeminen on harvinaista.)

Poistotoiminto sisältyy päivitykseen myös.
