### ISSUE TITLE
Ilmoittautumislomake - asiakasnumeron luonti

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#24]
Leirilaskutusla varten tarvítaan asiakasnumero. Se ei nyt kuitenkaan synny jo ilmoittautumisen yhteydessä vaan se luodaan käsin järjestelmän ulkopuollella ja myöhemmin tuodaan tietokantaan.

Vaatimus: kun käyttäjä painaa "ilmoitaudu", niin samalla syntyisi käyttäjän asiakasnumero muodossa 'vvvvnnnn'.

**Comment by aevik** [comment]
Todettakoon, että tällainen asiakasnumeron generointitoiminto voidaan toteuttaa aivan hyvin jollakin muullakin/uudellakin moduulilla tai PHP-koodilla, eikä sen aikaansaaminen vaadi, että asiakasnumerot tehdään juuri ilmoittautumislomakemoduulilla. Laskutusjärjestelmä ei edellytä, että asiakasnumero on luotu juuri ilmoittautumishetkellä tai että asiakasnumeron järjestysnumero vastaa ilmoittautumisjärjestystä.

**Comment by anwolski** [comment]
Sama kuin #25
