### ISSUE TITLE
Ilmoittautumislomake - liittyminen perhejäsenyyteen - käsittely

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#26]
Ilmolomakkeen kohta:
![ekapv-perhe](https://user-images.githubusercontent.com/16022208/68549084-f2e5a680-03fc-11ea-9761-fa29b1bdd4c1.png)

Tämä tieto siirretään toimistolle käsiteltäväksi. Hyvin usein ihmiset ilmoittavat asiakasnumeron (joka näkyy laskussa), koska postinsaajan jäsennumeroa ei tiedetä. Se on yhtä hyvä perhejäsenyyden toteamiseen kuin jäsennumero.

Ehdotukset:
1) tekstiin lisätään "tai asiakasnumero (löytyy laskusta)" (**KIIRELLINEN**)
ja lisäksi 
2) lisätään automaattinen jäsennumeron ja asiakasnumeron tarkistus. (EI KIIRELLINEN)

**Comment by anwolski** [comment]
Teksti "tai asiakasnumero (löytyy laskusta)" lisätty 11.11.2019

**Comment by aevik** [comment]
Tämä teksti lisättiin. Mainittakoon, että kun minulta asiasta ennalta kysyttiin, tulkitsin asian pelkästään tekstimuotoilukysymykseksi, ja sellaiseksi se on otettukin. Vaikka kentän otsikkoa muutettiin, tikettiin ei sisältynyt linjausta toiminnallisuuksien laajentamisesta, ts. taustatyökalut sisältävät toistaiseksi automaatiota kentän tietojen käsittelyyn vain, jos on annettu nimenomaan jäsennumero.
