### ISSUE TITLE
Ilmoittautumislomake - jäsentyypin koodaus oikeaksi

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#28]
Ilmoittautumislomakeella taulun protu_jasenhakemukset jäsentyyppii on koodattu seuraavaksi

1 = yksilöjäsen
2 = perhejäsen

Oikea koodaus (sama kuin jasenkortti-taulussa) on:

1 = perhejäsen
2 = yksilöjäsen

Toimeenpiteet:
1) vaihda lomakeen koodia
2) konvertoi jo olemassa olevat arvot protu_jasenhakemukset-taulussa
3) päivitä taulun liittyvät kyselyt
4) päivitä ilmojäsenhakemusten työkalua
3) päivitä laskutus

**Comment by aevik** [comment]
Lisäsin tähän itseni vastuulliseksi - toki vain kohtien 1-4 osalta
