### ISSUE TITLE
Uusi työkalu: muuta ilmoittautumisten tilat: 'vahvistettu' -> 'laskutuksessa'

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#29]
Tämä tarvitaan leirilaskutuksen yhteydessä sen jälkeen, kun kaikki 'vahvistettu'-tilassa olevat ilmoittautumiset ovat viety reskontraan. Kysessä on tämän SQL-komennon suorittamisestä:
----------
UPDATE registration
INNER JOIN node node_leiri ON registration.entity_id = node_leiri.nid AND node_leiri.type = 'leiri'
INNER JOIN field_data_field_leiri_ajankohta leiri_ajankohta ON node_leiri.nid = leiri_ajankohta.entity_id
/* change*/
SET registration.state = 'in_billing'
/* Where-ehdot */
WHERE registration.type = 'leiri_ilmoittautuminen'
  AND registration.state = 'confirmed'
  AND YEAR(leiri_ajankohta.field_leiri_ajankohta_value) = 2020
---------
HUOM: SQL-haku -sivu ei hväksy UPDATE-komentoja

**Comment by lanttupeikko** [comment]
Esimerkki sivusta, jolla on php-koodia: budjetin syöttämislomake

**Comment by anwolski** [comment]
Tehty PHP:lla
