### ISSUE TITLE
International-leiriläistilastot – sivu rikki?

### ISSUE THREAD

**Issue by janirutanen** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#3]
International-leirien ilmoittautumistilastot (https://www.protu.fi/jasenalue/materiaalipankki/international-leirien-leiril%C3%A4istilastot) näyttää osan leiriläisistä syntymävuoden väärin (siinä näkyy toimistosihteeri Eevan syntymävuosi). Vika koskee niitä, jotka eivät ole tehneet ilmoittautumistaan sivuilla itse vaan joiden leiri-ilmoittautumisen toimisto on syöttänyt järjestelmään heidän puolestaan toimistotunnuksilla.

**Comment by janirutanen** [comment]
Vika ei ole kyseisen ilmoittautumisjärjestelmän tai mainitun tilastosivun koodissa (tarkistettu!) vaan taustalla pyörivässä tilastointiohjelmassamme, joka on kirjannut tilastoinnin lokiin year_of_birth-kentän syntymävuoden väärin tapauksissa, joissa henkilön ilmoittautuminen on syötetty eri käyttäjätunnuksella.

Pitää sekä korjata taustakoodi että päivittää virheellisesti tallentuneiden ilmoittautumisten tiedot oikeiksi.

**Comment by aevik** [comment]
Vian taustalla ollut koodivirhe on korjattu, mutta vanhat tiedot pitää vielä päivittää ajantasalle. Uusiin ilmoittautumisiin ei pitäisi tuota virhettä enää tulla.

**Comment by anwolski** [comment]
Aiheeton, sivu toimii
