### ISSUE TITLE
Ilmoittautumislomake - lomake väittää jäseneksi, vaikka ei ole

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#30]
Seuraavaasa skenariossa:

Käyttäjä luo uuden jäsenhakemusen (vanhalle lomakeelle)  
-> käyttäjä avaa ilmoittautumislomakkeen (lukee "olet jo jäsen")
-> toimisto poistaa hakemuksen tällä:
https://www.protu.fi/node/211/webform-results
-> käyttäjä avaa ilmoottautumislomakeen (lukee "olet jo jäsen")

Eli jäsenhakemus on "liimautunut" jonnekin, vaikka sitä ei ole missään tietokanassa (tarkistettu).

**Comment by aevik** [comment]
Hakemus löytyi protu_jasenhakemukset-taulusta.
