### ISSUE TITLE
Leiri - jäsentietojen lisäys leiriläisten listaan tiimiläisille

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#31]
Koska nykyisin jäsenyyden vaikutus ulottuu leirille asti (korun hinta), niin tiimiläisten on nähtavä, onko leiriläinen jäsen vai ei. Tämä liitty leirikorun hintaan ja myös siihen, kenelle kohdistetaan jäsenhakua ja kenelle ei.

**Comment by aevik** [comment]
Olikohan kyseessä Protu_signup_lists-moduuli? En ole varma.

**Comment by anwolski** [comment]
Irrelevant
