### ISSUE TITLE
"Luo uusi käyttäjätili" -lomake: huoltajan osoitteen kopioinnin helpottaminen

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#32]
Tämä on laskutuksen näkökulma: huoltajaosoitetiedot usein (20% tapauksissa) puuttuvat, koska niitä ei täytetä, kun ajatellaan "no, kun se sama, kuin leiriläisen, sen pitäisi olla selvä". No, se on selvä siinä mielessä, että toimisto kopioi näissä tapauksissä leiriläisen osoitteen huoltajan osotteeksi. Sama juttu jäsenlaskutuksissa. Nämä eivät mene tietokantaan (olisi liian paljon käsityötä). Asia toistuu siis uudelleen ja uudelleen jäsenlaskutuksissa.

Asian helpottamiseksi lomakeessa pitäsi olla ruksi "Sama osoite kuin yllä" ja koodi, joka kopioi osoitteen tietokannan sopivaan kohtaan. (Huluamme pitää ne kuitenkin erillään).

**Comment by aevik** [comment]
Laskutuskyselyn koodia on syytä muokata niin, että jos ilmoitetulle huoltajalle ei ole tallennettu osoitetta, kysely hakee kenttään leiriläisen oman osoitteen.

**Comment by aevik** [comment]
Käyttäjän rekisteröitymiseen ei ole mahdollista lisätä kriteeriä, joka pakottaa syöttämään huoltajan tiedot, jos oma ikä on alle 18 v.

**Comment by anwolski** [comment]
Laskutuksen yhteydessä.
