### ISSUE TITLE
Rekryjen kyselyt omalle sivulle

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#37]
On olemassa joukko kyselyjä, jotka palvelevat rekryjä. Rekry eivät kuitenkaan pääse katsomaan SQL-kyseljä. Nämä kyselyt voidaan siirtää omalle sivulle ja antaa rekryille oikeudet.

**Comment by aevik** [comment]
Rekryjen on hyvä aukisanoittaa tarkka formaatti, missä tiedot haluavat. Jos haluavat selata tietoja sivuilla, on tiedot syytä antaa muussa muodossa, kuin jos ne on tarkoitus kopioida Exceliin ja käsitellä siellä.

Lisäksi: Jos rekryt tarvitsevat tiedot vain tiimien kokoamiseen, onko perusteltua antaa kaikille rekryille pääsy kaikkiin näihin tietoihin ympäri vuoden?

**Comment by anwolski** [comment]
Antoni selvittää tarpeet

**Comment by anwolski** [comment]
Luotu/korjattu kaksi sivua:
https://www.protu.fi/yllapito/tiimipalautetilanne
https://www.protu.fi/rekryt/koulutuksettomat

Muita pyyntöjä ei tullu
