### ISSUE TITLE
Rekryjen oikeudet sivulla

### ISSUE THREAD

**Issue by janirutanen** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#4]
Järjestelmässä on kolme erilaista rekry-roolia: _Rekry_, _Rekry-pj_ ja _Rekry-extra_. _Rekry-extra_-lienee tarkoitettu annettavaksi yksittäiselle rekrylle pj:n tueksi tilapäisesti, esim. jos rekryjen tiimienkokoamisviikonloppuun pitäisi hakea järjestelmästä SQL-kyselynä rekrykortit massana.

Käytännössä niiden välillä permissioneissa ei ole nykyisin Drupal 7 -migraation myötä muuta eroa, kuin että tavis-rekry ei ole
- päässyt käsiksi SQL-hakuun
- voinut poistaa rekrykortteja (Rekrykortti: delete own content / delete any content)

Ilmeisesti aiemmin ennen järjestelmäuudistusta eroja on ollut enemmänkin.

Kaikilla Rekry-roolillisille pitäisi ainakin saada oikeudet tiimiroolien myöntämiseen (myös jatkoleiritiimeihin sekä muuhun jälkirekrytointiin).

Eli täytyy tarkistaa rekryjen nykyiset oikeudet ja miettiä etenkin tuo tiimiläisroolien myöntämisen käytäntö ja turvakeinot.

**Comment by anwolski** [comment]
Vanhentunut, odotetaan uusia vaatimuuksia.
