### ISSUE TITLE
Paikkatiedot: osoite ja kunta

### ISSUE THREAD

**Issue by janirutanen** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#5]
Sähköposti 17.3.2016 (vastaanottajat www-työryhmä, toimisto, leirijaosto):

(teksti tiivistetty)

> Joskus alussa postinumeron viereen on pantu kunnan nimi. Se oli väärin, koska viralliseen postiosoitteeseen kuuluu postitoimipaikan eikä kunnan nimi. Tietokannassa on molemmat tiedot: toimipaikka ja kunta
> 
> Nyt paikkanäkymissä näkyy oikea osoite (melkein, esim. tässä näkymässä on ylimääräinen pilkku:
> https://www.protu.fi/prometheus-leirit/leirit ) mutta kunnan nimi katosi, vaikka oli siellä ennen järjestelmäremonttia.
> 
> Ehdotan, että palautetaan kunnan nimi ainakin paikan päänäkymään (esim. tässä:
> https://www.protu.fi/node/550 lukisi osoite-ryhmässä osoitteen alla "Kunta: Sauvo"). Lisäksi kunnan nimen muokkaaminen pitäisi saada takaisin muokkausnäkymään.

**Comment by aevik** [comment]
Asia on otettu käsittelyyn. Työ on keskeisiltä tiedoiltaan valmis, mutta ulkoasua pitää vielä fiksata.

**Comment by janirutanen** [comment]
> Sivulla on ulkoasussa pientä bugia yhä: postinumeron ja postitoimipaikan välissä ei ole välilyöntiä ja kunnan nimi on tyhmästi boldattu otsikkonsa lailla. Valitettavasti en saanut tätä äsken korjattua; fiksataan, kun pystytään.
> 
> Jos halutaan olla tarkka osoitteiden kanssa, niin tässä on vielä kaksi pientä bugia.
> Leirinäkymässä
> https://www.protu.fi/prometheus-leirit/leirit/halslahti_2016-06-12
> ja leirilistassa paikan mukaan:
> https://www.protu.fi/prometheus-leirit/leirit
> 
> on tarpeeton pilkku postinumeron ja toimipaikan välillä.

**Comment by aevik** [comment]
Viat on muuten saatu korjattua, mutta itse tapahtumapaikan esittelysivulla (esim. https://www.protu.fi/node/216) näkyy vielä pilkku kunnan nimen perässä, ja Kunta-otsikko on eri rivillä. Näiden korjaus on vielä kesken.
![sieppaa](https://cloud.githubusercontent.com/assets/14886557/15990479/0148b7b8-309c-11e6-9321-d7cb6b63e03a.PNG)

**Comment by anwolski** [comment]
9.11.2019. Kaikki näyttää olevan kunnossa.
