### ISSUE TITLE
Ohjeet yhdistyksestä eroamiseen puuttuvat sivuilta

### ISSUE THREAD

**Issue by aevik** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#6]
Ainakin yksi jäsen etsi tietoa eikä onnistunut sitä löytämään.

**Comment by janirutanen** [comment]
Toimistolla (Santerilla) ollut joku visio aiheesta, mutta ei tietoa onko asia edennyt.

**Comment by anwolski** [comment]
Ratkaistu.
