### ISSUE TITLE
Rekrykorttien ja aikataulutoivelomakkeiden tyhjentäminen

### ISSUE THREAD

**Issue by aevik** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#8]
Tiimit on koottu, nykyiset rekrykortit ja kesäleiritiimeihin (!) jätetyt aikataulutoivelomakkeet tulisi tyhjentää tarpeettomina.

**Comment by janirutanen** [comment]
Rekrykortit tyhjentämättä. Views on rikki migraation jäljiltä. Korjaan paremmalla ajalla.

**Comment by janirutanen** [comment]
Näkymä korjattu ja rekrykorttien poistoon on nyt oikeudet adminilla sekä rekry-pj:llä: https://www.protu.fi/admin/rekrykortit/korttien_poisto
