### ISSUE TITLE
Kunnan näkyvyys tapahtumapaikkanäkymässä

### ISSUE THREAD

**Issue by anwolski** [protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset#9]
Tietokannassa on molemmat tiedot: toimipaikka ja kunta. Joillekin (esim. kaupungilaisille) on vaikea käsittää, että ne ovat kaksi eri asiaa, mutta se vain on näin. Viralliseen osoitteseen kuulu vain toimipaikka.

Nyt paikkanäkymissä näkyy oikea osoite (no melkein, esim. tässä näkymässä on ylimääräinen pilkku:
https://www.protu.fi/prometheus-leirit/leirit )

... mutta kunnan nimi katosi, vaikka oli siellä ennen järjestelmäremonttia. Sen takia joku nyt lähtee väittämään, että Halslahti on Sauvossa eikä Karunassa. Kas, kun toinen on toimipaikka ja toinen kunta.

Ehdotan, että palautetaan kunnan nimi ainakin paikan päänäkymään, esim. tässä:

https://www.protu.fi/node/550

... lukisi osoite-ryhmässä osoitteen alla "Kunta: Sauvo"

Myös päitäisi paluttaa kunnan nimen muokkausnäkymään.

HUOM: En missään tapauksessa toivo, että toimipaikan tilalle laitetaan kunnan nimi. Järjestelmän alkuvaiheessä tämäkin virhe on tehty.

**Comment by aevik** [comment]
Tämä löytyy jo tikettinä https://github.com/protu-www/Protun-www-sivujen-korjaukset-ja-kehitykset/issues/5
